:: Daysim Result Calculation - Generated by Honeybee

SET RAYPATH=.;c:\radiance\lib;C:\DAYSIM\bin\;C:\DAYSIM\lib;
PATH=c:\radiance\bin\;C:\DAYSIM\bin\;C:\DAYSIM\lib;$PATH
:: Generate the result files
ds_el_lighting.exe  C:\Users\adao\Desktop\Glasgow_Uni_Parametric\Floor_0_0_Glazing_0_4_VerticalShade_0_250_HorizontalShade_0\annualSimulation\Floor_0_0_Glazing_0_4_VerticalShade_0_250_HorizontalShade_0_0_space_0.hea
